#!/bin/bash

# unicode symbol
uSMILE='\u263A'
uFROWN='\u2639'
uCHECK='\u2611'
uWRONG='\u2612'

# color constants
cRED="\e[01;31m"
cGREEN="\e[01;32m"
cYELLOW="\e[01;33m"
cBLUE="\e[01;34m"
cPURPLE="\e[01;35m"
cTURQUOISE="\e[01;36m"
cLIGHTGRAY="\e[00m"

# color with non-printing char (to correctly calculate word-wrapping)
ccRED='\[\e[01;31m\]'
ccGREEN='\[\e[01;32m\]'
ccYELLOW='\[\e[01;33m\]'
ccBLUE='\[\e[01;34m\]'
ccPURPLE='\[\e[01;35m\]'
ccTURQUOISE='\[\e[01;36m\]'
ccLIGHTGRAY='\[\e[00m\]'

# background color
bDARKGRAY='\e[40m'
bRED='\e[41m'
bGREEN='\e[42m'
bYELLOW='\e[43m'
bBLUE='\e[44m'
bPURPLE='\e[45m'
bTURQUOISE='\e[46m'
bLIGHTGRAY='\e[47m'


# Color info
# Attribute codes:
#     00=none
#     01=bold
#     04=underscore
#     05=blink
#     07=reverse
#     08=concealed

# Text color codes:
#     30=black
#     31=red
#     32=green
#     33=yellow
#     34=blue
#     35=magenta
#     36=cyan
#     37=white

# Background color codes:
#     40=black
#     41=red
#     42=green
#     43=yellow
#     44=blue
#     45=magenta
#     46=cyan
#     47=white
colors-info() {
	local fgc bgc vals seq0

	printf "Color escapes are %s\n" '\e[${value};...;${value}m'
	printf "Values 30..37 are \e[33mforeground colors\e[m\n"
	printf "Values 40..47 are \e[43mbackground colors\e[m\n"
	printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"

	# foreground colors
	for fgc in {30..37}; do
		# background colors
		for bgc in {40..47}; do
			fgc=${fgc#37} # white
			bgc=${bgc#40} # black

			vals="${fgc:+$fgc;}${bgc}"
			vals=${vals%%;}

			seq0="${vals:+\e[${vals}m}"
			printf "  %-9s" "${seq0:-(default)}"
			printf " ${seq0}TEXT\e[m"
			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
		done
		echo; echo
	done
}
